language: go

go: 1.7.x

sudo: required

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD";
    ./build.sh;
    ./push.sh;
    fi
